version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    # Only use this to bump our libraries
    allow:
      - dependency-name: "unstructured[all-docs]"

  - package-ecosystem: "github-actions"
    # NOTE(robinson) - Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
